Repository open-guides/og-aws, pull requests merged in 2018-10, with the labels that each got.

#639 Adds detail about cross-region RDS Aurora read replica limit
  README.md
Labels: final review, sec: Redshift

#640 Update Cloudwatch compliance
  README.md
Labels: sec: Product Matrix

#655 Updated for new version support of MariaDB and MySQL
  README.md
Labels: review wanted, sec: RDS
